name: slt_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.3.0
  image_picker: ^1.1.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  socket_io_client: ^3.1.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  path: ^1.9.1
  photo_view: ^0.14.0
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1
  connectivity_plus: ^6.1.4
  sqflite: ^2.2.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  flutter_sound: ^9.28.0
  pin_code_fields: ^8.0.0
  lottie: ^3.0.0
  blur: ^3.0.0
  audio_waveforms: ^1.0.4
  device_info_plus: ^11.0.0
  flutter_cache_manager: ^3.3.2
  file_picker: ^10.2.0
  flutter_pdfview: ^1.4.0+1
  video_player: ^2.10.0
  flutter_launcher_icons: ^0.13.1
  badges: ^3.1.2
  video_thumbnail: ^0.5.6
  syncfusion_flutter_pdfviewer: ^28.1.38
  sqflite_sqlcipher: ^2.1.0+1
  flutter_secure_storage: ^9.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/bg_4.jpg
     - assets/main_bg.png
     - assets/users.png
     - assets/splash_screen/logo.png
     - assets/splash_screen/slider_1.png
     - assets/splash_logo.png
     - assets/user-2.png
     - assets/login.json
     - assets/logo.png
     - assets/sounds/chat_send.mp3
     - assets/chat_send.mp3
     - assets/upcomming.mp3
  #   - images/a_dot_ham.jpeg

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_screen/logo.png
  android_gravity: center
  android_12:
    image: assets/splash_screen/logo.png
    icon_background_color: "#ffffff"
  ios_content_mode: center
  fullscreen: true
  web: false 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"